### ISSUE TITLE
Dll not found exception

### ISSUE THREAD

**Issue by Sujilonline** [Corey-M/NAudio.Lame#10]
Hello all, while trying to convert wav to mp3, am getting the following exception
DllNotFoundException: winmm.dll
NAudio.Wave.WaveFileReader.ReadWaveHeader (System.IO.Stream stream, NAudio.Wave.WaveFormat& format, System.Int64& dataChunkPosition, System.Int32& dataChunkLength, System.Collections.Generic.List`1 chunks)
NAudio.Wave.WaveFileReader..ctor (System.IO.Stream inputStream)
NAudio.Wave.WaveFileReader..ctor (System.String waveFile)
(wrapper remoting-invoke-with-check) NAudio.Wave.WaveFileReader:.ctor (string)
ConvertWavToMp3.WaveToMP3 (System.String waveFileName, System.String mp3FileName, Int32 bitRate) (at Assets/ConvertWavToMp3.cs:54)

Can anyone help me to fix this?
When imported the package, I was getting an error related to the namespace using NAudio.Wave. Later I added the NAudio dll separately then the error resolved.  But while trying to convert the wav, still stuck with above error

**Comment by markheath** [comment]
what operating system are you running on?

**Comment by Sujilonline** [comment]
I need to use this plugin for Mac, windows, android and iOS

**Comment by markheath** [comment]
winmm.dll is part of windows. You need to find another way to do cross-platform audio I'm afraid. Maybe PortAudio can help?

**Comment by Corey-M** [comment]
Mark is correct.  In addition the Lame DLLs are Windows-native and will not work on other platforms.
