### ISSUE TITLE
Trial Sound in recordings

### ISSUE THREAD

**Issue by umartechboy** [Corey-M/NAudio.Lame#17]
I'm hearing a "Trial" sound in all of the recordings....  is it the case with everyone?

**Comment by Corey-M** [comment]
Not hearing this in my own tests.  What was the issue?

**Comment by umartechboy** [comment]
I've replied to my own post. The issue was resolved. It comes to be an
issue in my setup. I was using a virtual wire solution to loop back music
through my microphone for development. The sound was coming through that.

I first migrated to another OGG encoder. But ASAP I realized what issue
was, I replied to my comment on GitHub.

Thanx for your time!!

Umar
