### ISSUE TITLE
MP3 to Wave

### ISSUE THREAD

**Issue by smohammedyasin** [Corey-M/NAudio.Lame#19]
Hello, 
this is not an issue. just a question.
i have a situation to reduce mp3 file 128 to 64kbs.  for that i need to convert into .wav and re convert to .mp3 i believe. 
so, can i use this dll to convert from mp3 to wav?

Please advice me ,
Thank you

**Comment by Corey-M** [comment]
Hi @smohammedyasin 

Converting MP3 to MP3 is simply a matter of opening the source file (using `NAudio.Wave.AudioFileReader` for instance) and then writing it out with the appropriate properties.  `LameMP3FileWriter` has [a constructor][1] that accepts a bitrate in kb/s, so you can specify the value you need.

For instance:

    public static void AudioFileToMP3_64K(string sourceFileName, string destFileName)
    {
        using (var reader = new AudioFileReader(sourceFileName))
        using (var writer = new LameMP3FileWriter(destFileName, reader.WaveFormat, 64))
            reader.CopyTo(writer);
    }
        
This will work for any audio file supported by `NAudio` as long as it satisfies the [restrictions][2] of the LAME MP3 library:

* 1 or 2 channels
* Wave format is 16-bit `Pcm` or 32-bit `IeeeFloat`
* Sample rate is betwen 8kHz and 48kHz (inclusive)

For your use case (source files in MP3 format) this should not present any issues as the files will already satisfy the restrictions.

[1]:https://github.com/Corey-M/NAudio.Lame/blob/master/MP3FileWriter.cs#L261-L268
[2]:https://github.com/Corey-M/NAudio.Lame/blob/master/MP3FileWriter.cs#L279-L289

**Comment by Corey-M** [comment]
Closing as no updates in ~4 weeks.
