### ISSUE TITLE
NullReferenceException in LameMP3FileWriter.ApplyID3Tag

### ISSUE THREAD

**Issue by skaa** [Corey-M/NAudio.Lame#21]
There should be a check for null value of `UserDefinedTags`:
```
string[] userDefinedTags = tag.UserDefinedTags;
for (int i = 0; i < userDefinedTags.Length; i++)
{
```

**Comment by Corey-M** [comment]
The code you posted isn't part of the library.  Are you referring to the [code in `ApplyID3Tag`][1] that sends the tag data to the `LAME` dll for inclusion?

Not sure why that one got through testing previously.  Have patched it now.

[1]:https://github.com/Corey-M/NAudio.Lame/blob/master/MP3FileWriter.cs#L631-L637
