### ISSUE TITLE
Looks like 1.0.5 does not support .Net 4.0

### ISSUE THREAD

**Issue by jwallet** [Corey-M/NAudio.Lame#22]
It took me sometimes to get why LameMp3Writer was always returning : 
`Object reference not set to an instance of an object`
from this code:
```
writer = new LameMP3FileWriter(
                        GetFileName(_path + insertArtistDir, _song, "mp3"),
                        waveIn.WaveFormat,
                        _bitrate,
                        tag);
                    return writer;
```

After downgrading to 1.0.4 everything was working fine. Just wanted to let you know. Maybe you added a note of this version on Nugget package but I did not see it. I'm not asking for a fix btw and also thanks for this great package.

edit: i'm up to date with NAudio : v1.8.2

**Comment by Corey-M** [comment]
Sorry @jwallet, this was fixed [in the code][1] but I hadn't updated the NuGet package.  The error was in the way that the IDv3 tag was handled... I didn't test the new code properly before I deployed.

v1.0.6 now fixes this.

Incidentally, the target platform for the library is .Net40, although I could probably back that down to .Net35 to line up with NAudio.  I'll look into that at a future date.

[1]: https://github.com/Corey-M/NAudio.Lame/blob/master/MP3FileWriter.cs#L631-L637
