### ISSUE TITLE
install.ps1 is retired from Package Reference

### ISSUE THREAD

**Issue by xycui** [Corey-M/NAudio.Lame#27]
install.ps1 is not called since the Nuget is updated. Is it possible to use the method mentioned [here](https://tyrrrz.me/Blog/Additional-NuGet-files-in-new-csproj) to create a new Nuget package? Thanks in advance.

**Comment by Corey-M** [comment]
Try the new v1.0.8 package I uploaded just now.  It uses a `.targets` file to ensure that the native libraries get copied to the output directory during build.

**Comment by xycui** [comment]
Thanks a lot. :)
