### ISSUE TITLE
Assemblies are not signed.

### ISSUE THREAD

**Issue by shafaqat309** [Corey-M/NAudio.Lame#28]
I am trying to reference in a SharePoint project which will deploy assemblies into GAC, I am getting error that assemblies are not signed. I have tried to sign the assemblies but then getting compile error. could you please upload signed assemblies package through Nuget?

**Comment by Corey-M** [comment]
Sorry but NAudio is not strongly signed, so there is no hope of signing this project.

Perhaps if you raise an issue on [NAudio](1) Mark might put a signature on, then I can do the same for this.

1: https://github.com/naudio/NAudio/issues
