### ISSUE TITLE
No .NET standard support

### ISSUE THREAD

**Issue by robvangeloven** [Corey-M/NAudio.Lame#29]
Is it possible to bump the framework version used? The NuGet package doesn't work with .NET Standard 2.0 libraries anymore since release 1.0.8

**Comment by Corey-M** [comment]
So now I know how to use .Net Standard.  A little.

I haven't committed the code yet - it's still too ugly for that - but there's a preview package on NuGet that targets netstandard2.0 so it should support .NET 4.6.1 and .NET Core 2.0 or above.

This is my first try at a netstandard* NuGet package, so it'll probably be horribly wrong.  Let me know how it goes.

Assuming that the package loads it should be fully functional.  Play with it a bit and let me know how badly it breaks.  I'll clean up the code and sync it at some point.

**Comment by Corey-M** [comment]
@robvangeloven New 1.1.0-pre2 is reworked as .Net Standard all the way through.  On Core you need to call `Loader.Init`()` (see issue #33) before you do anything with it though.

**Comment by Corey-M** [comment]
@robvangeloven New pre-release on NuGet (v1.1.0-pre3) should have fewer problems than pre2.  Check it out, let me know if it works for you.

**Comment by Corey-M** [comment]
OK, no feedback for a while, but people seem to be using 1.1.0.  I assume this is resolved.  Open a new issue if not.

Oh, and Happy New Year.
