### ISSUE TITLE
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection

### ISSUE THREAD

**Issue by JayH77** [Corey-M/NAudio.Lame#31]
Hi,

I am trying to convert a WAV file to MP3 (this works fine for MP3 to MP3) using the following code:

using (var reader = new NAudio.Wave.AudioFileReader(Server.MapPath(my_upload_path))) { using (var writer = new NAudio.Lame.LameMP3FileWriter(Server.MapPath(my_converted_path), reader.WaveFormat, 64)) { reader.CopyTo(writer); } }

But I'm getting the following error:

System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
at System.IO.BinaryReader.Read(Byte[] buffer, Int32 index, Int32 count)
at NAudio.Wave.WaveFormat.FromFormatChunk(BinaryReader br, Int32 formatChunkLength)
at NAudio.FileFormats.Wav.WaveFileChunkReader.ReadWaveHeader(Stream stream)
at NAudio.Wave.WaveFileReader..ctor(Stream inputStream, Boolean ownInput)
at NAudio.Wave.WaveFileReader..ctor(String waveFile)
at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
at NAudio.Wave.AudioFileReader..ctor(String fileName)
at portal.UserControls.ModalAssessmentAudio.ConvertAudioFileUsingLame()
at portal.UserControls.ModalAssessmentAudio.ProcessAudioFile()]

**Comment by Corey-M** [comment]
That looks like a problem with your original WAV file.  According to that stack trace the error is happening during the construction of your `AudioFileReader`.  Specifically the source file seems to have a malformed format header.

I'd suggest you open that file with VLC or similar and see what the actual format is.

**Comment by JayH77** [comment]
Hi Corey-M,

Thanks for the quick reply.

POTPlayer gave me the following info:

Complete name                  : F:\aaaaaaaa.WAV
Format                         : Wave
File size                      : 40.5 MiB
Duration                       : 29 min 28 s
Overall bit rate mode          : Constant
Overall bit rate               : 192 kb/s

Audio
Format                         : ADPCM
Codec ID                       : 11
Codec ID/Hint                  : Intel
Duration                       : 29 min 28 s
Bit rate mode                  : Constant
Bit rate                       : 192 kb/s
Channel(s)                     : 1 channel
Sampling rate                  : 48.0 kHz
Bit depth                      : 4 bits
Stream size                    : 40.5 MiB (100%)

VLC gave me the following:

Codec: http://prntscr.com/nraaz9
Statistics: http://prntscr.com/nrabb5 (These numbers keep increasing, second by second?)

If the conversion fails, it falls to the 2nd conversion using MediaToolkit (which works on these files) so it's a not a major problem but thought I'd post just in case it's not an issue with the files.

Thanks again

**Comment by Corey-M** [comment]
That looks fine, I've had plenty of files that look similar to that.  The stack trace however seems to indicate that it's a problem with NAudio opening the file.  Can you try a minimal program that just opens the file with NAudio (without the NAudio.Lame nuget loaded) and see if it fails there?  If so this might be an interesting case for Mark Heath on the main NAudio package.

If the file isn't sensitive can you link it here or something so I can try to figure out what's going wrong?  Or a sample file that causes the same problem, since that one is half an hour long.  It sounds like a fun challenge.

**Comment by Corey-M** [comment]
I've put a .NET Standard 2.0 pre-release package up on NuGet.  Can you please try that one and see if it changes the error you are getting at all.  It's a whole new build with a stack of slight changes, nothing that should be particularly relevant, but maybe we'll get lucky.

And I'm still keen to see a sample that reproduces the error.

**Comment by Corey-M** [comment]
OK, no feedback for a while, but people seem to be using 1.1.0.  I assume this is resolved.  Open a new issue if not.

Oh, and Happy New Year.
