### ISSUE TITLE
The type or namespace name 'Lame' does not exist in the namespace 'NAudio' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by teknoalex** [Corey-M/NAudio.Lame#33]
I installed with NuGet Package manager but using NAudio.Lame doesn't work :[

**Comment by Corey-M** [comment]
Hi @teknoalex , I'm going to need some more information here.  What development environment are you using?  Do you have a recent version of NuGet installed?  Also, can you try this with the latest preview version (v1.1.0-pre2) and tell me if the problem is resolved?

**Comment by Corey-M** [comment]
@teknoalex Can you please try with the latest pre-release on NuGet (v1.1.0-pre3) and let mw know if this works.  pre1 and pre2 had some issues that are now (hopefully) resolved.

**Comment by teknoalex** [comment]
@Corey-M "v1.1.0-pre3" doesn't show up in NuGet Package manager. Do I have to update a repository or the package manager for it to show up or do I have to somehow compile it from GitHub? (this is my first .net project 🤠)

**Comment by teknoalex** [comment]
Thank you very much. It finally works. I really like that I just had to exchange 1 line of code to use mp3 instead of wav

**Comment by Xerotherm1c** [comment]
I'm getting the same issue, but my project is a .NET 4.6 Class Library. I have verified that I cannot import NAudio.Lame in this project after having tried both 1.1.2 (released 4 days ago) and 1.1.0-pre3 as requested above in this thread. I don't even see it listed in the dependencies (only regular NAudio is in the project dependencies). Please advise. Thanks!

**Comment by Corey-M** [comment]
@Xerotherm1c This seems to happen when an older version of NAudio is already present in the package list.  Can you try updating to the latest NAudio release and see if that fixes the issue?
