### ISSUE TITLE
Missing properties assignment in lame initialization

### ISSUE THREAD

**Issue by teo-a** [Corey-M/NAudio.Lame#39]
Since your rework of the lame initialization in [this commit](https://github.com/Corey-M/NAudio.Lame/commit/6172e1608c50c1bec9f1539a68b1bd9add471336), the InputSampleRate and NumChannels properties of the LibMp3Lame class are not set anymore (previously done [here](https://github.com/Corey-M/NAudio.Lame/commit/6172e1608c50c1bec9f1539a68b1bd9add471336#diff-1d836c93e57737e851d5917c8d3498ceL140) and [here](https://github.com/Corey-M/NAudio.Lame/commit/6172e1608c50c1bec9f1539a68b1bd9add471336#diff-1d836c93e57737e851d5917c8d3498ceL214)).

Is it just a small oversight or is there a new way to set thoses properties ?

Thank you anyway for this very useful wrapper !

**Comment by Corey-M** [comment]
I moved the bulk of the lame initialisation to the LameConfig class.  The call to `config.ConfigureDLL()` on [line 178][1] handles all the pre-encoding configuration including [quality or bitrate][2] setup.  The constructors that take quality or bitrate all chain to the main constructor, passing quality or bitrate in the `LameConfig` instance ([line 97][3] and [line 117][4]).

If this isn't working I'll have to do some tests and fix it.  Have you gotten a bad output or was the source change confusing?  I mean, yes, my source changes are often unclear... but is it working wrong for you?

[1]: https://github.com/Corey-M/NAudio.Lame/blob/6172e1608c50c1bec9f1539a68b1bd9add471336/NAudio.Lame/LameMP3FileWriter.cs#L178
[2]: https://github.com/Corey-M/NAudio.Lame/commit/6172e1608c50c1bec9f1539a68b1bd9add471336#diff-0cdf3f4c3e084bb2dc06dfb54f8e3ed3R110-R114
[3]: https://github.com/Corey-M/NAudio.Lame/blob/6172e1608c50c1bec9f1539a68b1bd9add471336/NAudio.Lame/LameMP3FileWriter.cs#L97
[4]: https://github.com/Corey-M/NAudio.Lame/blob/6172e1608c50c1bec9f1539a68b1bd9add471336/NAudio.Lame/LameMP3FileWriter.cs#L117

**Comment by teo-a** [comment]
My problem is specifically with InputSampleRate. My input wave file has a sample rate of 8000Hz, by default the InputSampleRate is initialised to 44100Hz, and I did not find how to change it to reflect my input file sample rate. InputSampleRate was previously set to format.SampleRate is the two location I linked in my first port.

If I try to convert it with InputSampleRate = 44100Hz (default), the output file is speeded up and its duration went from 44 sec to 8 sec.

I should've included this in the first post, sorry.

Here is how I create the LameMP3FileWriter, if it can help :
`var mp3Writer = new LameMP3FileWriter(outMp3Stream, inStream.WaveFormat, LAMEPRESET.V0))`

**Comment by jdeksup** [comment]
I have the same problem here. The input sample rate should be 16000Hz, the output file is then speeded up.

**Comment by Corey-M** [comment]
Well, gee, that's a bit embarrassing.  Let me fix that.  And add a test for it.

**Comment by Corey-M** [comment]
@teo-a @jdeksup OK, this is fixed.  Please try the new version in NuGet: v1.1.2.

**Comment by teo-a** [comment]
Thank you for fixing it, Its now working like a charm !
