### ISSUE TITLE
ConvertSourceToMP3 0xffffe885

### ISSUE THREAD

**Issue by 13640535881** [Corey-M/NAudio.Lame#41]
Convert Amr To MP3 Error! 

/*****code*****/
       public void ConvertSourceToMP3(string inputFilePath = "test.amr", string outFilePath = "test.mp3")
        {
            //using (var reader = new AudioFileReader(inputFilePath))
            //using (var writer = new LameMP3FileWriter(outFilePath, new WaveFormat(16000, 1), 128))
            //    reader.CopyTo(writer);

            using (var reader = new MediaFoundationReader(inputFilePath))
                MediaFoundationEncoder.EncodeToMp3(reader, outFilePath, 128000);
        }

please help! thanks

**Comment by Corey-M** [comment]
Sorry, `MediaFoundationEncoder.EncodeToMp3(...)` is not part of this library. Please check in with Mark over on the [`NAudio`][1] project.

[1]: https://github.com/naudio/NAudio
