### ISSUE TITLE
Request: Read ID3 tags from an mp3 file

### ISSUE THREAD

**Issue by ftamminga** [Corey-M/NAudio.Lame#44]
It would be great if you would add the possibility to read ID3 tags from an mp3 file.
Now I have to add yet another NuGet package, just to do that.

**Comment by Corey-M** [comment]
If you look at the ID3 tests (specifically the [`ReadID3v2Tag`()][1] method) there's some simple code to extract the ID3v2 tag from a stream as `byte[]` whcih can then be parsed by the [`ID3Decoder.Decode()`][2] method.

The test code isn't particularly safe or pretty but it is fairly small, and `NAudio.Lame.ID3Decoder` is public so you should be able to use it.

If it's a bit deal I could move the tag reader into `ID3Decoder` I guess.

[1]: https://github.com/Corey-M/NAudio.Lame/blob/master/Lame.Test.Core/T03_ID3Tag.cs#L105
[2]: https://github.com/Corey-M/NAudio.Lame/blob/master/NAudio.Lame/ID3Decoder.cs#L45

**Comment by Corey-M** [comment]
Doing some housekeeping here, going to close this one off.  Reopen if you want me to work on this.
