### ISSUE TITLE
LAMEPreset V0 to V9 has no effect 

### ISSUE THREAD

**Issue by johanneshhl** [Corey-M/NAudio.Lame#47]
It seems that the LAME-Presets are not having a effect on the conversions. 
I've tried all 10 and they all produce the same file 80kb file.

This is on net core v. 3.1.302

`{
        
            using (var reader = new AudioFileReader("C:/tmp/source.wav")) 
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V0.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V0, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V1.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V1, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V2.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V2, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V3.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V3, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V4.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V4, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V5.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V5, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V6.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V6, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V7.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V7, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V8.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V8, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }
            
            using (var reader = new AudioFileReader("C:/tmp/source.wav"))
            using (var writer = new LameMP3FileWriter("C:/tmp/LAMEPreset_V9.mp3", reader.WaveFormat, new LameConfig { Preset = NAudio.Lame.LAMEPreset.V9, Mode = NAudio.Lame.MPEGMode.JointStereo }))
            {
                reader.CopyTo(writer);
            }

        }
`

**Comment by Corey-M** [comment]
The presets were in the header so I added them without any inspection of how they function.

Looking into it, the `V0`-`V9` quality settings set the encoder to use VBR at varying levels of allowed quantization error. In theory `V0` should produce larger files than `V9`. But the kicker is that they only work when VBR mode has been set. I assumed (incorrectly as it happens) that VBR would be enabled while applying the preset, but apparently that's up to the user to do.

I'll update `LameConfig` to enable VBR if you use the `V0`-`V9` presets and add `VBRMode` to the exposed configuration.

**Comment by Corey-M** [comment]
Fixed in v1.1.4.  Uploading to NuGet now.
