### ISSUE TITLE
Enhance LameConfig to support more VBR options

### ISSUE THREAD

**Issue by jasonleenaylor** [Corey-M/NAudio.Lame#52]
We would like to be able to control down sampling and also the minimum and maximum variable bitrate as well as set the algorithm quality 

Lame command line options:
-a, -b, -B, -q, -F  (when using a VBR option)

**Comment by Corey-M** [comment]
I've got a few busy days ahead.  Will try to get to this next week, but my history of updates isn't particularly consistent. Any chance you'd put a PR together for it? 😛

**Comment by Corey-M** [comment]
Check out the latest code.  I added most of the VBR stuff, plus maybe a couple of other things. Have a look and see if it does what you need now.  If not, let me know what's missing.

v1.1.6 is up on NuGet.
