### ISSUE TITLE
NAudio.Lame and fody.costura

### ISSUE THREAD

**Issue by VicLo2020** [Corey-M/NAudio.Lame#59]
Hello

I am using fody.cosura in my project to include the .dll in the executable.
When I call LameMP3FileWriter, I get the error:
Could not load file or assembly "LameDLLWrap, Version = 2.0.0.0, Culture = neutral, PublicKeyToken = null" or one of its dependencies. The parameter is set incorrectly. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

How can this problem be solved?

Using:
VS2019
NAudio.Lame last version

**Comment by Corey-M** [comment]
NAudio.Lame does manually what Costura.Fody does. There are two copies of the LameDLLWrap assembly, compiled for 32- and 64-bit, stored as resources. This was a (fun but slightly silly) choice I made early on to avoid having to either maintain duplicates of a large collection of p/invoke code or using manual linkage to a lot of library methods. It works in most simple cases, but loading NAudio.Lame from a resource could well break things.

It's possible that the module initializer isn't being called properly, so you could try manually invoking it:

    NAudio.Lame.ModuleInitializer.Initialize();

If that doesn't work then you may be stuck with excluding NAudio.Lame from the process using Costura's `ExcludeAssemblies` config option and ship the assembly with your executable. That or grab the relevant parts of the code and add it to your project directly.

**Comment by VicLo2020** [comment]
Hello.
NAudio.Lame.ModuleInitializer.Initialize(); -  did not help.
This method is called automatically.
The place where the exception occurs:

internal static bool LoadNativeDLL(params string[] rootPaths)
{
...
var paths = rootPaths
.concat(new[]
{
AppDomain.CurrentDomain.BaseDirectory,
Path.GetDirectoryName(typeof(LameDLL).Assembly.Location)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).ToArray();

typeof(LameDLL).Assembly.Location == ""

**Comment by Corey-M** [comment]
Ah, OK. I didn't consider when writing that code that the NAudio.Lame class would be loaded from an in-memory assembly. In some cases where the NAudio.Lame assembly isn't in the `BaseDirectory` (which can happen in some ASP.NET scenarios) that needs to be checked, but I can work around the error at least.

**Comment by Corey-M** [comment]
Uploaded a small patch. Can you build it on your end and confirm for me that it solves the issue?

**Comment by VicLo2020** [comment]
Hello
I tested this change on my project and it works.
Thank you.
P.S: Waiting for update in NuGet for easy usage :)

**Comment by Corey-M** [comment]
Sorry, took me a bit to get into my NuGet account. I use it like once a year 😄 

v2.0.1 updated.

**Comment by VicLo2020** [comment]
Thank you
