### ISSUE TITLE
Signed dll

### ISSUE THREAD

**Issue by sullivanets1** [Corey-M/NAudio.Lame#61]
Hello,

I am attempting to include this functionality in a .net 4.7.2 website project.

Unfortunately I haven’t been able to execute the code, the project requiring signed dll’s.

I saw a closed issue here with someone else requesting signed dll:
https://github.com/Corey-M/NAudio.Lame/issues/28

It was mentioned in that issue that NAudio was not signed, since that date it now is, as noted here:
https://github.com/naudio/NAudio/pull/677

Would it be possible for you to create a signed version of this functionality please?

**Comment by Corey-M** [comment]
Sorry @sullivanets1 but code signing isn't on my list of things to achieve with this, since it requires me to maintain keys and all that across multiple devices (I develop on at least 6 machines in different locations). You're more than welcome to build and sign your own version however.
