### ISSUE TITLE
Needs update for NAudio.Core V2.1

### ISSUE THREAD

**Issue by CrashM85** [Corey-M/NAudio.Lame#69]
Hi, When trying to use this with NAudio.Core V2.1 i get the following error:

    Exception type: FileLoadException 
    Exception message: Could not load file or assembly 'NAudio.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

When i downloaded your project and updated the dependancy for NAudio.Core from v2,0 and v2.1 and rebuilt it, it worked in my project.

**Comment by Corey-M** [comment]
Should be fixed now. Reopen if you're still having issues.
