### ISSUE TITLE
libmp3lame.64.dll can't be deleted

### ISSUE THREAD

**Issue by kylemarcus** [Corey-M/NAudio.Lame#7]
Hi - I am using your library to convert wav files to mp3 files in a web api.  Everything works fine except when trying to build or deploy which will try to overwrite the libmp3lame.64.dll in the bin folder of the web api project.  It says its not able to replace the file because its being used by the IIS worker process.

I have been trying to test this to see what is going on and not too sure how to solve this?  Seems like the dll reference is not being closed after using it?

I am simply doing the following in the web api

public static byte[] ConvertWavToMp3(byte[] wavFile)
{
            using (var retMs = new MemoryStream())
            using (var ms = new MemoryStream(wavFile))
            using (var rdr = new WaveFileReader(ms))
            using (var wtr = new LameMP3FileWriter(retMs, rdr.WaveFormat, 128))
            {
                rdr.CopyTo(wtr);
                return retMs.ToArray();
            }
        }

**Comment by Corey-M** [comment]
This is a known issue with IIS and native DLLs, and is fundamental to how IIS operates.

In .NET applications using P/Invoke to access entry points in native DLLs the DLL is loaded into the process space on the first call to an entry point.  The native DLL then remains loaded into the process memory space, and the DLL file itself is locked, until the process terminates.  As long as the process remains open the DLL will be locked for delete, write, etc.  For a desktop application this simply means that you need to close the program to terminate the process, thus releasing the file lock and allowing you to replace the DLL.

On IIS the process that runs your code is owned by the Application Pool that your website is configured to use, and could be several processes running on the same AppPool.  Those processes don't close until the AppPool is stopped or recycled, so any native DLLs that are loaded into the process space are held open.

In general the solution is to recycle the AppPool to release the loaded native DLLs.  [This article][1] on TechNet shows how to recycle the AppPool with a few options: manually through IIS Manager, via a script on the IIS server or remotely via WMI.

One point though... the native Lame DLLs haven't changed so don't actually need to be updated.  Could you setup your deploy system to ignore files that haven't changed?  This would stop it from failing on the native DLLs when it can't update them, until the files have actually changed.

[1]: https://technet.microsoft.com/en-us/library/cc770764%28v=ws.10%29.aspx

**Comment by kylemarcus** [comment]
Thanks for the info! I have modified our deploy process to work around this.

**Comment by Gh61** [comment]
Workaround for anyone stumbling across this issue and using IIS + WebDeploy.
We just edited our pubxml profiles to look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your Web project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project>
  <PropertyGroup>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>

    ...
    
    <!-- vvv Required for the MSDeploySkipRules to work vvv -->
    <UseMsdeployExe>true</UseMsdeployExe>
    <DeployManagedPipelineMode>Integrated</DeployManagedPipelineMode>
  </PropertyGroup>

  <!-- Skip existing mp3lame dll update - library never changes, but is locked by iis due to [DllImport] -->
  <!-- Based on: https://stackoverflow.com/questions/12576662/msdeploy-skip-rules-when-using-msbuild-publishprofile-with-visual-studio-2012 -->
  <!-- Issue: https://github.com/Corey-M/NAudio.Lame/issues/7 -->
  <!-- Alternative solution: Rewrite NativeMethods.cs (https://github.com/Corey-M/NAudio.Lame/blob/master/LameDLLWrap/NativeMethods.cs) to use LoadLibrary/FreeLibrary instead of [DllImport] -->
  <ItemGroup>
    <MsDeploySkipRules Include="SkipMp3Lame64Dll">
      <SkipAction>Update</SkipAction>
      <ObjectName>filePath</ObjectName>
      <AbsolutePath>bin\\libmp3lame\.64\.dll$</AbsolutePath>
    </MsDeploySkipRules>
    <MsDeploySkipRules Include="SkipMp3Lame32Dll">
      <SkipAction>Update</SkipAction>
      <ObjectName>filePath</ObjectName>
      <AbsolutePath>bin\\libmp3lame\.32\.dll$</AbsolutePath>
    </MsDeploySkipRules>
  </ItemGroup>

</Project>
```

I think I see an alternative in rewriting the `NativeMethods.cs` file to use native `LoadLibrary` and then manually getting pointers to methods using `GetProcAddress` method. Then propagate some possibility to to unload the library by using native `FreeLibrary` method.
This way the consumer could release the library anytime he wants.
