### ISSUE TITLE
Length of encoded audio signal increases compared to the origin

### ISSUE THREAD

**Issue by Wieland-der-Schmied** [Corey-M/NAudio.Lame#70]
First of all many thanks to @Corey-M for his nice work!
I am programming an exporter and importer for our measurement files. Unfortunately after exporting to MP3 the duration of the audio signal is longer than the duration of the origin signal. I just tried different configurations (LameConfig) but nothing helped. Then I found this in the internet: [https://stackoverflow.com/questions/18493779/length-of-mp3-encoded-with-lame](https://stackoverflow.com/questions/18493779/length-of-mp3-encoded-with-lame)
But I don't know how to realize it with NAudio.Lame. And I don't know if it is the right solution at all.
To us it is very important that the length of our measurement recordings does not change by transmitting them throug MP3.
Any help possible?

**Comment by Wieland-der-Schmied** [comment]
There might be another reason for the expansion of the audio signal: [http://mp3decoders.mp3-tech.org/decoders_lame.html#:~:text=All%20mp3%20encoders%20and%20decoders%20introduce%20a%20small,and%20decoded%20via%20lame%20incur%20no%20overall%20delay.](url)

**Comment by Corey-M** [comment]
Well that could explain it. 

There's a flag ([`LameConfig.WriteVBRTag`][1]) that controls whether or not the VBR frame is written. I haven't done much testing on that part, but you can set it by creating your own `LameConfig` and setting `WriteVBRTag` to true, then pass that as to the constructor of `LameMP3FileWriter`. After the constructor the setting is fixed into the encoder configuration, and I don't expose the encoder handle so you can't set it after the fact. At the end of encoding when [`LameMP3FileWriter.Flush`][2] is called (don't do it before the end of the input by the way) if that flag was set then it will write the tag.

And yes, I probably need to fix that so it writes the tag by default when VBR or ABR are enabled.

Anyway, give it a go and let me know if it resolves the issue for you. And good catch by the way.

[1]: https://github.com/Corey-M/NAudio.Lame/blob/5b5bb009d8c63ef8ab95cb36ca9105c8acc1c5fc/NAudio.Lame/LameConfig.cs#L103
[2]: https://github.com/Corey-M/NAudio.Lame/blob/5b5bb009d8c63ef8ab95cb36ca9105c8acc1c5fc/NAudio.Lame/LameMP3FileWriter.cs#L283-L309

**Comment by Corey-M** [comment]
Oh, on the other part - the encoder/decoder delay - there's not much to be done about it when using LAME or pretty much any of the other MP3 codecs. All of them introduce delays of some sort, although LAME does try to eliminate as much of that as possible during decode. It's a moving target apparently.

**Comment by Wieland-der-Schmied** [comment]
I think that I now found the main reason: https://lame.sourceforge.io/tech-FAQ.txt
Nevertheless the update of the header (lame frame) after writing the audio data could be a goot idea for NAudio.Lame too: https://stackoverflow.com/questions/18493779/length-of-mp3-encoded-with-lame
